apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-{{ .Values.name }}
spec:
  storageClassName: {{ .Values.storage.class }}
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
